Capstone
ridaarif98/capston pull request #1
Opened 2021-07-07 18:23 UTC by ridaarif98

This is a capstone project using HTML, CSS, and javascript.

- All HTML pages are responsive according to screen size
- Popup menu for mobile view
- Display speakers info using javascript object
- Integrate linter
- Resolve linter errors

2021-07-08 11:46 UTC, Temmarie requested changes
## STATUS: CHANGES REQUIRED! :recycle:

### Hi @ridaarif98     ! :wave: :wave:

#### You have done really well in implementing the requirements.
- You used proper GitHub Flow ✔️ 
- Your linter checks are all passing ✔️ 
- Your README and PR message are descriptive ✔️ 

 However, there are changes required for you to make in order for this project to be approved. 
- - -

### **Required Changes** ♻️
_See the inline comments below for more required changes_


### Optional Changes 👌
Every comment with the OPTIONAL prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend that you take them into account as they can make your code better.
- N/A
_If anything doesn't seem clear to you, feel free to leave your question or comment in the PR thread below_

**_"Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise."_**
- - - 
**_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._**
__Kindly make the necessary changes and submit another code review request.__

2021-07-08 11:46 UTC, Temmarie commented on index.html
> +        </nav>
- [ ] You have a blank space at the top of the navbar, kindly remove it.
- [ ] Also, space out the logo and nav items, the logo should be to the extreme left.
- [ ] The last nav item should have a border around it, kindly add this.
- [ ] Also, use the correct background colour here, it shouldn't be black, it should be `#272A31`


_See images below_

**Original** | **Your project**
  ----------- | -----------
  ![image](https://user-images.githubusercontent.com/49621279/124913352-df109000-dfa3-11eb-9456-88bd89532385.png) | ![image](https://user-images.githubusercontent.com/49621279/124913439-f8b1d780-dfa3-11eb-9e00-598dfaf2627d.png)

2021-07-08 11:46 UTC, Temmarie commented on index.html
> +    </section>
- [ ] Good job dynamically rendering the speakers here 👍🏾 
- There's a little tweak to make tho: 
You are missing the image shadow decoration on the top left corner. Kindly add this.

_See images_

**Original** | **Your project**
  ----------- | -----------
  ![image](https://user-images.githubusercontent.com/49621279/124914629-6ca0af80-dfa5-11eb-96e7-61e860c4ffec.png) | ![image](https://user-images.githubusercontent.com/49621279/124914737-8f32c880-dfa5-11eb-9aa1-b4627a69f0c2.png)

2021-07-08 11:46 UTC, Temmarie commented on about.html
> +  </footer>
- [ ] On the About page, the footer has just one dark part.

_See images_

**Original** | **Your project**
  ----------- | -----------
  ![image](https://user-images.githubusercontent.com/49621279/124915919-eedda380-dfa6-11eb-83ac-386ef67b8628.png) | ![image](https://user-images.githubusercontent.com/49621279/124915987-02890a00-dfa7-11eb-9d96-0d3b9029150e.png)

2021-07-08 11:46 UTC, Temmarie commented on index.html
> +    </footer>
- [ ] KIndly use the correct colour for the lower footer. It shouldn't be white but `#d3d3d3`

2021-07-09 09:22 UTC, Temmarie requested changes
## STATUS: CHANGES REQUIRED! :recycle:

### Hi @ridaarif98     ! :wave: :wave:

#### You have done really well in implementing the previously required changes.

 However, there are changes required for you to make in order for this project to be approved. 
- - -

### **Required Changes** ♻️
- [ ] You've done an amazing job overall, but it seems while making the required changes, some styles broke in your code. Kindly fix them

_See the inline comments below for the required changes_


### Optional Changes 👌
Every comment with the OPTIONAL prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend that you take them into account as they can make your code better.
- N/A

_If anything doesn't seem clear to you, feel free to leave your question or comment in the PR thread below_

**_"Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise."_**
- - - 
**_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._**
__Kindly make the necessary changes and submit another code review request.__

2021-07-09 09:22 UTC, Temmarie commented on about.html
> +          <p class="emailInfo">womensummit2021@america.org</p>
- [ ] This page has a horizontal overflow due to this section on mobile. Kindly fix this.

_See image below_

![image](https://user-images.githubusercontent.com/49621279/125054250-de870080-e05a-11eb-90ec-f302b112dc71.png)

2021-07-09 09:22 UTC, Temmarie commented on index.html
> +            </ul>
- [ ] Kindly adjust this section on mobile screens to be properly aligned. You also have a horizontal overflow on this screen size.

_See images below_

**Original** | **Your project**
  ----------- | -----------
  ![image](https://user-images.githubusercontent.com/49621279/125055295-e2675280-e05b-11eb-95b3-b25670ee6116.png) | ![image](https://user-images.githubusercontent.com/49621279/125055393-fe6af400-e05b-11eb-953a-f88d8092ccac.png)

2021-07-09 09:22 UTC, Temmarie commented on index.html
> +    </section>
- [ ] Good job adding the background shadow to the images, kindly reduce the size of the shadow and the image and make the colour a light grey(`#d3d3d3`).

2021-07-09 10:39 UTC, mikenath223 approved these changes
Hello there  

Your project is complete!  There is nothing else to say other than... it's time to merge it 🛳 
Congratulations! 🎉 

Happy coding. Cheers! 🚀🚀

If you feel something isn't clear enough you can leave a question or comment in the PR thread.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-09 10:45 UTC, mikenath223 commented on about.css
> +  } */
- [ ] OPTIONAL- Kindly remove this commented out code-block. If you need to refer to previous versions of the code please use Git History.

2021-07-09 10:46 UTC, mikenath223 commented on about.css
> +  border: 3px solid #F7F7F7; */
- [ ] OPTIONAL - Kindly remove this comment also.

2021-07-09 11:11 UTC, merged